Fix build break: remove stray brace in utils.cc
Dedup of GetTensorShape in 93a24db copied the anonymous-namespace
closer from reshape_transpose_rank5.cc into utils.cc, which has no
anonymous namespace. Extra '}' broke every onnxruntime_providers_qnn
compile (ubuntu/arm64/windows/android/coverage/asan) with:
utils.cc:507:1: error: expected declaration before '}' token